INTEX/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recruiters/', include('recruiters.urls')),
    path('', include('seekers.urls')),
]

recruiters/urls.py
from django.urls import path
import recruiters.views as v
from seekers.views import loginView

app_name = 'Recruiters'
urlpatterns = [
    # path("applicant_listings", v.applicantListingsView, name="Applicant Listings"),
    path("listing/addListing", v.AddListingView, name="CreateJob"),
    path('listing/editListing/<str:ListingID>', v.EditListingView, name='EditListing'),
    path('listing/deleteListing/<str:ListingID>', v.DeleteListingView, name='DeleteListing'),
    path('listing/addSkill/<str:ListingID>', v.AddListingSkill, name='AddListingSkill'),
    path('listing/editSkill/<str:ListingSkillID>', v.EditListingSkillView, name='EditListingSkill'),
    path('listing/deleteSkill/<str:ListingSkillID>', v.DeleteListingSkillView, name='DeleteListingSkill'),
    path("listing/applicants", v.applicantsView, name="Applicants"),
    path('listing/login/', loginView, name='Login'),
]   

seekers/urls.py
from django.urls import path
import seekers.views as v  

app_name = 'Seekers'
urlpatterns = [
    path("job_listings", v.jobListingsView, name="JobListings"),
    path("profile/<str:Type>/<str:userID>", v.profileView, name="Profile"),
    path("apply/<str:ListingID>", v.applicationView, name="Application"),
    # path("search", v.searchJob, name="Search"),
    # path('results', v.SearchResultsView, name='SearchResults'),
    path("create_account/<str:AccountType>", v.CreateAccountView, name="CreateAccount"),
    path("login", v.loginView, name="Login"),
    path("logout", v.logoutView,name="Logout"),
    path("about", v.about, name ="About"),
    path("add_skills", v.AddSeekerSkillsView, name="AddSkills"),
    path('editSkills/<str:SeekerSkillID>', v.EditSeekerSkillsView, name='EditSkills'),
    path('deleteSkills/<str:SeekerSkillID>', v.DeleteSeekerSkillsView, name='DeleteSkills'),
    path("search_bar/<str:SearchString>", v.SearchBar, name="SearchBar"),
    path("userApplications", v.userApplicationsView, name="UserApplication"),
    path("trending_jobs", v.recommenderDisplayView, name="TrendingJobs"),
    path("learn_more", v.learnMoreView, name="LearnMore"),
    path("", v.IndexPageView, name="Index"),
]   

recruiters/models.py
"""
Models for the Recruiters app.

Models:
    Recruiter: profile for a Recruiter User
"""
# Python Imports

# Django Imports
from django.db import models
from django.contrib.auth.models import User
# App Imports
from recruiters.choices import SECTOR, SIZE

# pylint:disable=no-member

class Recruiter(models.Model) :
    """
    Profile for a Recruiter user.
    
    Posts jobs, sorts through Job Seekers, and extends offers.

    Attributes: 
        user: OneToOne -> User, on_delete CASCADE
        org: CharField(max_length 100)
        emp_job_title: CharField(max_length 50)
    """
    user = models.OneToOneField(to=User, on_delete=models.CASCADE)
    org = models.CharField(verbose_name='Organization', max_length=100)
    emp_job_title = models.CharField(verbose_name='Employee Job Title', max_length=50)
    class Meta :
        # makes life easier by allowing a simple permission test
        permissions= [
            ('is_recruiter', 'Is a Recruiter')
        ]
    
    def __str__(self):
        return str(self.user.get_full_name())

recruiters/forms.py
"""
Forms used by the Recruiters app. 

Forms:
    PostJobForm: Allows a Recruiter to post Listings to the site.
    AddListingSkillForm: Allows a Recruiter to add Skills to a Listing.
"""
# Python Imports

# Django Imports
from django import forms
from django.forms import ValidationError
# App Imports
from recruiters.choices import SIZE, SECTOR
from seekers.choices import SKILL_LEVEL, RELOCATION_ASSISTANCE
from seekers.models import ContractType, ContractLength, ListingSkill, Skill

# pylint:disable=no-member

class PostJobForm(forms.Form) :
    """
    Used by Recruiters to post a Listing to the site. 

    Fields:
        job_title: Charfield 
        job_description: Charfield 
        location: CharField 
        contract_type: ModelChoiceField -> ContractType 
        contract_length: ModelChoiceField -> ContractLength 
        salary_upper: DecimalField(max_digits 8, decimal places 2)
        salary_lower: DecimalField(max_digits 8, decimal_places 2)
        reloc: CharField(choices RELOCATION_ASSISTANCE)
    """
    job_title = forms.CharField(label='Job Title')
    job_description = forms.CharField(label='Job Description', widget=forms.Textarea)
    location = forms.CharField(label='Location')
    contract_type = forms.ModelChoiceField(
        queryset=ContractType.objects.all().order_by('contract_type'), 
        label='French Contract Type:'
        )
    contract_length = forms.ModelChoiceField(
        queryset=ContractLength.objects.all().order_by('contract_length'), 
        label='Contract Term:'
        )
    salary_upper = forms.DecimalField(
        max_digits=8, 
        label='What is the salary upper limit for this job?', 
        decimal_places=2
        )
    salary_lower = forms.DecimalField(
        max_digits=8, 
        label='What is the salary lower limit for this job?', 
        decimal_places=2)
    reloc = forms.CharField(
        label='Relocation assistance available?', 
        widget=forms.Select(choices=RELOCATION_ASSISTANCE)
        )

    def clean_salary_lower(self) :
        sl =  self.cleaned_data.get('salary_lower')
        su = self.cleaned_data.get('salary_upper')
        if sl > su :
            raise ValidationError('The salary lower limit should be less than the upper limit!')
        # need to return a value or it will be a none
        return self.cleaned_data.get('salary_lower')

class AddListingSkillForm(forms.Form) :
    """
    Used by Recruiters to add a Skill to a Listing.

    Fields: 
        skill: ModelChoiceField->Skill 
        level: CharField(choices SKILL_LEVEL)
        is_required: BooleanField 
    """
    skill = forms.ModelChoiceField(queryset=Skill.objects.all().order_by('skill_name'))
    level = forms.CharField(
        max_length=1,
        widget=forms.Select(choices=SKILL_LEVEL)
        )
    is_required = forms.BooleanField(
        label='Is required?', 
        help_text='If left unchecked, it indicates that the skill is preferred.', 
        required=False
        )

recruiters/views.py
"""
View functions for the Recruiters app.

Functions:
    applicantsView: displays all applicants to a Listing.
    AddListingView: allows a Recruiter to add a Listing.
    EditListingView: allows a Recruiter to edit a Listing.
    DeleteListingView: allows a Recruiter to delete a Listing.
    AddListingSkillView: allows a Recruiter to add a Listing Skill.
    EditListingSkillView: allows a Recruiter to edit a Listing Skill.
    DeleteListingSkillView: allows a Recruiter to delete a Listing Skill.
"""
# Python Imports

# Django Imports
from django.db import IntegrityError
from django.forms import ValidationError
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required, permission_required
# App Imports
from recruiters.forms import PostJobForm, AddListingSkillForm
from recruiters.models import Recruiter, User
from seekers.models import Listing, Skill, ListingSkill, ContractLength, ContractType

# pylint:disable=no-member

@login_required()
@permission_required('recruiters.is_recruiter', raise_exception=True)
def applicantsView(request) :
    """
    Displays all Job Seekers that have applied to a Listing.

    GET:
        Shows a Recruiter the applicant's to their Listings.

        Args:
            None
    """
    recruiter = Recruiter.objects.get(user=request.user)
    jobs = Listing.objects.filter(posted_by=recruiter)

    context = {   
        "recruiter" : recruiter,
        "jobs" : jobs,
    }
    return render(request, 'recruiters/applicants.html', context=context)

@login_required()
@permission_required('recruiters.is_recruiter', raise_exception=True)
def AddListingView(request) :
    """
    Allows a Recruiter to create a new job listing 

    GET:
        Return a blank form for the Recruiter to fill out.

        Args:
            None
    POST:
        Create the Listing from the form the Recruiter filled out and 
        redirects them to their profile to verify it went through.
    """
    # check the request method
    # if GET, render blank form
    if request.method == 'GET' :
        context = {
            'form': PostJobForm(),
        }
        return render(request, 'recruiters/postJob.html', context=context)
    # if POST, create the listing and send the recruiter to the profile page
    elif request.method == 'POST' :
        form = PostJobForm(request.POST)
        # check if form is valid
        # if valid, add the listing
        if form.is_valid() :
            job_title = form.cleaned_data.get('job_title')
            job_description = form.cleaned_data.get('job_description')
            location = form.cleaned_data.get('location')
            contract_length = form.cleaned_data.get('contract_length')
            contract_type = form.cleaned_data.get('contract_type')
            poster = Recruiter.objects.get(user=request.user)
            salary_upper = form.cleaned_data.get('salary_upper')
            salary_lower = form.cleaned_data.get('salary_lower')
            reloc = form.cleaned_data.get('reloc')
            
            Listing.objects.create(
                listing_job_title=job_title, 
                job_description=job_description, 
                location=location, 
                contract_length=contract_length, 
                contract_type=contract_type, 
                posted_by=poster, 
                salary_lower=salary_lower, 
                salary_upper=salary_upper, 
                relocation_assistance=reloc
                )
            # send the Recruiter to their profile
            return redirect(reverse('Seekers:Profile', kwargs={'Type': 'recruiter', 'userID': request.user.pk}))
        # if invalid form, render the Post Job page with the form's errors
        else :
            return render(request, 'recruiters/postJob.html', context={'form': form})
    # invalid method 
    else :
        return HttpResponse('i am an invalid method on the post job view')
    
@login_required()
@permission_required('recruiters.is_recruiter', raise_exception=True)
def EditListingView(request, ListingID):
    """
    Allows a Recruiter to edit a listing previously posted.

    GET: 
        Returns the Listing data in a form for the Recruiter to edit.
        
        Args:
            ListingID: pk of the Listing to be edited
    POST:
        Saves the changes made on the form to the model and redirects the 
        Recruiter to their profile to verify it went through.
    """
    # checks the request method
    # if GET, return the listing for review
    if request.method == 'GET' : 
        listing = Listing.objects.get(pk=ListingID)
        # creates the intital data to populate the form with
        intialData = {
            'job_title': listing.listing_job_title,
            'job_description': listing.job_description,
            'location': listing.location,
            'contract_length': listing.contract_length,
            'contract_type': listing.contract_type,
            'salary_upper': listing.salary_upper,
            'salary_lower': listing.salary_lower,
            'reloc': listing.relocation_assistance,
        }
        context = {
            'form': PostJobForm(intialData),
            'ListingID': listing.pk,
            'ListingSkills': ListingSkill.objects.filter(listing=listing),
        }
        # renders the form
        return render(request, 'recruiters/postJob.html', context=context)
    # if POST, save the data and redirect to profile
    elif request.method == 'POST' :
        form = PostJobForm(request.POST) 
        # check if form is valid
        # if valid, proceed with update
        if form.is_valid() :
            updateListing = Listing.objects.get(pk=ListingID)

            updateListing.job_title = form.cleaned_data.get('job_title')
            updateListing.job_description = form.cleaned_data.get('job_description')
            updateListing.location = form.cleaned_data.get('location')
            updateListing.contract_length = form.cleaned_data.get('contract_length')
            updateListing.contract_type = form.cleaned_data.get('contract_type')
            updateListing.salary_lower = form.cleaned_data.get('salary_lower')
            updateListing.salary_upper = form.cleaned_data.get('salary_upper')
            updateListing.relocation_assistance = form.cleaned_data.get('reloc')
            updateListing.save()
            # redirect to the profile page
            return redirect(reverse('Seekers:Profile', kwargs={'Type': 'recruiter', 'userID': request.user.pk}))
        # if invalid, display the edit Page with the form errors
        else :
            return render(request, 'recruiters/postJob.html', context={'form': form,})
    # invalid method
    else :
        return HttpResponse('i am an invalid method on the edit listing view')

@login_required()
@permission_required('recruiters.is_recruiter', raise_exception=True)
def DeleteListingView(request, ListingID) :
    """
    Allows a Recruiter to delete a listing previously posted.
    
    GET:
        Returns a form with data to review prior to deletion.

        Args:
            ListingID: pk of the Listing object to delete
    POST:
        Deletes the selected Listing and redirects the Recruiter to their 
        profile to verify the deletion went through.
    """
    # checks the request method
    # if GET, renders the form with data populated
    if request.method == 'GET' :
        # gets the listing
        listing = Listing.objects.get(pk=ListingID)
        # populates the initial data dict
        intialData = {
            'job_title': listing.listing_job_title,
            'job_description': listing.job_description,
            'location': listing.location,
            'contract_length': listing.contract_length,
            'contract_type': listing.contract_type,
            'salary_upper': listing.salary_upper,
            'salary_lower': listing.salary_lower,
            'reloc': listing.relocation_assistance,
        }

        context = {
            'form': PostJobForm(intialData),
            'ListingSkills': ListingSkill.objects.filter(listing=listing),
            'Listing': listing.pk,
        }
        # render the template
        return render(request, 'recruiters/postJob.html', context=context)
    # if POST, delete the listing and reroute to profile view
    elif request.method == 'POST' :
        listingToDelete = Listing.objects.get(pk=ListingID)

        listingToDelete.delete()            
        # redirects to the profile to confirm delete
        return redirect(reverse('Seekers:Profile', kwargs={'Type': 'recruiter', 'userID': request.user.pk}))
    # invalid method
    else :
        return HttpResponse('I am a wrong method on the delete listing view')

@login_required()
@permission_required('recruiters.is_recruiter', raise_exception=True)
def AddListingSkill(request, ListingID) :
    """
    Adds a Skill to a Listing.

    GET: 
        Returns a blank form to allow a Recruiter to add a Skill to the Listing.

        Args:
            ListingID: pk of the Listing object to add a Listing Skill to
    POST:
        Adds the Skill to the Listing via the ListingSkill table and 
        redirects the Recruiter to their profile to verify it went 
        through.
    """
    # check the method
    # if GET, return a blank form
    if request.method == 'GET' :
        context = {
            'form': AddListingSkillForm(),
            'Listing': Listing.objects.get(pk=ListingID), 
        }   
        return render(request, 'recruiters/addSkill.html', context=context)
    # if POST, create a new ListingSkill object
    elif request.method == 'POST' :
        form = AddListingSkillForm(request.POST) 
        # check form for validation errors
        # if error raised, send them back to the form with the error message
        try :
            form.is_valid()

templates/recruiters/addSkill.html
{% extends 'base.html' %}
{% load static %} 
{% load seekers_extras %}

{% block nameOfTab %}
<title>Add Skills</title>
{% endblock %}

{% block header %}
<div class="container">
    <h1>Add a Skill to Your Listing</h1>
</div>
{% endblock  %}

{% block firstSection %}

<form action= "{{ request.get_full_path }}" method='POST'>
  <div class="container" style="border:1px solid #ccc">
    <h4>For the job listing {{Listing.listing_job_title}} at {{Listing.posted_by.org}}</h4>
    <hr>
    {% csrf_token %}

    {% for field in form %}
      {{ field.label_tag}}
      {{ field }}
      {{ field.errors }}
      <br>
    {% endfor %}

    {% if OtherSkills is not None %}
      <h6>These are the other skills associated with this listing:</h6>
      {% for skill in OtherSkills  %}
          <p>{{skill.skill.skill_name|title}} - Skill Level: {{skill.level|returnRating}} -  {% if skill.is_required %}Required{% else %}Preferred{% endif %}</p>
      {% endfor %}
    {% else %}
      <h6>There are no other skills associated with this listing!</h6>
    {% endif %}

    <div class="clearfix">
      {% if 'addSkill' in request.path %}
        <button type="submit" class="btn btn-primary" name="postJob">Add Skill</button>
      {% endif %}
      {% if 'editSkill' in request.path %}
        <button type="submit" class="btn btn-primary" name="saveChanges">Save Changes </button>
      {% endif %}
      {% if 'deleteSkill' in request.path %}
        <button type="submit" class="btn btn-primary" name="deleteJob">Delete Skill</button>
      {% endif %}
        <a href="{% url 'Recruiters:EditListing' ListingID=Listing.pk %}"><button type="button" class="btn btn-primary">Cancel</button></a>
    </div>
  </div>
</form>

{% endblock  %}

templates/recruiters/applicants.html
{% extends 'base.html' %}
{% load static %} 

{% block nameOfTab %}
  <title>Applicants</title>
{% endblock %}

{% block header %}
<div class="container applicants-center">
  <h1>Applications Submitted</h1>
</div>
{% endblock %}


{% block firstSection %}

<div class="container">
  <div class="row rowForJobListings" style="border:groove black">
    <div class="col-lg-12">
      <h3>Recruiter: {{ recruiter.user.first_name }} {{ recruiter.user.last_name}}</h3> 
      <h3>Organization: {{ recruiter.org }}</h3>
      <div class='applications'>
        {% for job in jobs %}
          <div class='applications-job-title'> <h4> Job Posting Title: {{ job.listing_job_title }} <h4> </div>
            <div class='application-row header'>
              <div class='application-row-item'> <h5> Applicant </h5> </div>
              <div class='application-row-item'> <h5> Contact </h5> </div>
              <div class='application-row-item'> <h5> Date Applied </h5> </div>
            </div>
          {% for applicant in job.application_set.all %} 
            <div class='application-row applicant'>
              <div class='application-row-item'> {{ applicant.seeker.user.first_name}} {{ applicant.seeker.user.last_name}} </div>
              <div class='application-row-item'> {{ applicant.seeker.user.email}} </div>
              <div class='application-row-item'> {{ applicant.date_applied}} </div>
            </div>
          {% empty %}
            <div class='application-row applicant'>
              <div class='application-row-item'> This listing has no applicants. </div>
            </div>
          {% endfor %}
          <br>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/recruiters/postJob.html
{% extends 'base.html' %}
{% load static %} 
{% load seekers_extras %}

{% block nameOfTab %}
  <title>Post a Job</title> 
{% endblock %}


{% block header %}
<div class="container">
  <h1>Post a Job Here!</h1>
</div>
{% endblock %}

{% block firstSection %}
<form action= "{{ request.get_full_path }}" method='POST'>
  <div class="container" style="border:1px solid #ccc">
    <h4>Please fill in this form to create a job listing.</h4>
    <br>

    {% csrf_token %}

    {% for field in form %}
      {{ field.label_tag}}
      {{ field }}
      {{ field.errors }}
      <br>
    {% endfor %}

    {% if ListingSkills is not None %}
      <h4>These skills are associated with this listing:</h4>
    {% endif %}

    {% for skill in ListingSkills  %}
      <p> 
      {{skill.skill.skill_name|title}} - Skill Level: {{skill.level|returnRating}} {% if skill.is_required %}Required{% else %}Preferred{% endif %} 
      <a href="{% url 'Recruiters:EditListingSkill' ListingSkillID=skill.pk %}"><button type="button" class="btn btn-primary">Edit</button></a> 
      <a href="{% url 'Recruiters:DeleteListingSkill' ListingSkillID=skill.pk %}"><button type="button" class="btn btn-primary">Delete</button></a> 
      </p>
    {% empty %}
      <p>No skills are associated with this listing yet. Click Add Skill to add a skill to this listing.</p>
    {% endfor %}

    <div class="clearfix">
      {% if 'addListing' in request.path %}
        <button type="submit" class="btn btn-primary" name="postJob">Post Job</button>
      {% endif %}
      {% if 'editListing' in request.path %}
       <button type="submit" class="btn btn-primary" name="saveChanges">Save Changes </button>
      {% endif %}
      {% if 'deleteListing' in request.path %}
        <button type="submit" class="btn btn-primary" name="deleteJob">Delete Listing</button>
      {% endif %}
        <a href="{% url 'Seekers:Profile' Type='recruiter' userID=user.pk %}"><button type="button" class="btn btn-primary">Cancel</button></a>
      {% if ListingID is not None %}
        <a href="{% url 'Recruiters:AddListingSkill' ListingID=ListingID %}"><button type="button" class="btn btn-primary">Add Skill</button></a>
      {% endif %}
    </div>
  </div>
</form>
{% endblock %}