INTEX/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recruiters/', include('recruiters.urls')),
    path('', include('seekers.urls')),
]

recruiters/urls.py
from django.urls import path
import recruiters.views as v
from seekers.views import loginView

app_name = 'Recruiters'
urlpatterns = [
    # path("applicant_listings", v.applicantListingsView, name="Applicant Listings"),
    path("listing/addListing", v.AddListingView, name="CreateJob"),
    path('listing/editListing/<str:ListingID>', v.EditListingView, name='EditListing'),
    path('listing/deleteListing/<str:ListingID>', v.DeleteListingView, name='DeleteListing'),
    path('listing/addSkill/<str:ListingID>', v.AddListingSkill, name='AddListingSkill'),
    path('listing/editSkill/<str:ListingSkillID>', v.EditListingSkillView, name='EditListingSkill'),
    path('listing/deleteSkill/<str:ListingSkillID>', v.DeleteListingSkillView, name='DeleteListingSkill'),
    path("listing/applicants", v.applicantsView, name="Applicants"),
    path('listing/login/', loginView, name='Login'),
]   

seekers/urls.py
from django.urls import path
import seekers.views as v  

app_name = 'Seekers'
urlpatterns = [
    path("job_listings", v.jobListingsView, name="JobListings"),
    path("profile/<str:Type>/<str:userID>", v.profileView, name="Profile"),
    path("apply/<str:ListingID>", v.applicationView, name="Application"),
    # path("search", v.searchJob, name="Search"),
    # path('results', v.SearchResultsView, name='SearchResults'),
    path("create_account/<str:AccountType>", v.CreateAccountView, name="CreateAccount"),
    path("login", v.loginView, name="Login"),
    path("logout", v.logoutView,name="Logout"),
    path("about", v.about, name ="About"),
    path("add_skills", v.AddSeekerSkillsView, name="AddSkills"),
    path('editSkills/<str:SeekerSkillID>', v.EditSeekerSkillsView, name='EditSkills'),
    path('deleteSkills/<str:SeekerSkillID>', v.DeleteSeekerSkillsView, name='DeleteSkills'),
    path("search_bar/<str:SearchString>", v.SearchBar, name="SearchBar"),
    path("userApplications", v.userApplicationsView, name="UserApplication"),
    path("trending_jobs", v.recommenderDisplayView, name="TrendingJobs"),
    path("learn_more", v.learnMoreView, name="LearnMore"),
    path("", v.IndexPageView, name="Index"),
]   

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content=""> 

  {% block nameOfTab %}
  <title>Black Cyber Recruiter Home</title>
  {% endblock %}

  <!-- Bootstrap core CSS -->
  <!-- <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet"> -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <!-- <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet"> -->
  <link href="{% static 'css/all.min.css' %}" rel="stylesheet">
  <!-- <link href="vendor/simple-line-icons/css/simple-line-icons.css" rel="stylesheet" type="text/css"> -->
  <link href="{% static 'css/simple-line-icons.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/landing-page.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/landing-page.css' %}" rel="stylesheet">
  <link href="{% static 'css/intex.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-light bg-light static-top">
    <div class="container"  style="display: flex;">
      <div style="flex-grow: 1;">
        <a class="navbar-brand" href="{% url 'Seekers:Index' %}">Black Cyber Recruiting</a>
      </div>
      <div>
        <a class="btn btn-primary" href="{% url 'Seekers:Index' %}">Home</a>
        <a class="btn btn-primary" href="{% url 'Seekers:JobListings' %}">Jobs</a>
        <a class="btn btn-primary" href="{% url 'Seekers:TrendingJobs' %}">Job Seeker+</a>

        {% if perms.recruiters.is_recruiter %}
          <a class="btn btn-primary" href="{% url 'Recruiters:CreateJob' %}">Post a Job</a>
          <a class="btn btn-primary" href="{% url 'Recruiters:Applicants' %}">View Applicants</a>
        {% endif %}

        <a class="btn btn-primary" href="{% url 'Seekers:About' %}">About Us</a>

        {% if perms.recruiters.is_recruiter %}
          <a class="btn btn-primary" href="{% url 'Seekers:Profile' Type='recruiter' userID=request.user.pk %}">Profile</a>
        {% elif perms.seekers.is_seeker %}
          <a class="btn btn-primary" href="{% url 'Seekers:Profile' Type='seeker' userID=request.user.pk %}">Profile</a>
        {% endif %}

        {% if user.is_authenticated %}
          <a class="btn btn-primary" href="{% url 'Seekers:Logout' %}">Logout</a>
        {% else %}
          <a class="btn btn-primary" href="{% url 'Seekers:Login' %}">Login/Create Account</a>
        {% endif %}
      </div>
    </div>
  </nav>

  <!-- Masthead --> 
{% block header %}
  <header class="masthead text-white text-center">
  <!-- <header class="masthead text-white text-center" style="background:url('img/bg-masthead.jpg') no-repeat center center;"></header> -->
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-xl-9 mx-auto">
          <h1 class="mb-5">Search for the Perfect Job!</h1>
        </div>
        <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
          <form action="{% url 'Seekers:SearchBar' SearchString='intern' %}" method='GET'>
            <div class="form-row">
              <div class="col-12 col-md-9 mb-2 mb-md-0">
                <input type="text" name='search' id='search' class="form-control form-control-lg" placeholder="Search by job title, location, company...">
              </div>
              <div class="col-12 col-md-3">
                <button type="submit" class="btn btn-block btn-lg btn-primary" id='search_submit'>Search</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </header>
{% endblock %}


{% block firstSection %}
  <!-- Icons Grid -->
  <section class="features-icons bg-light text-center">
    <div class="container" >
      <div class="row">
        <div class="col-lg-4">
          <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
            <h3>Looking for a Job?</h3>
            <p class="lead mb-0">Our website is guaranteed to provide you with your best employment opportunity. We know job searching is hard, that's why we are here to help.</p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
            <h3>Need to Post a Job?</h3>
            <p class="lead mb-0">Recruiters look no further. Black Cyber Recruiter is the best website on the internet for hiring minorities. Sign up today!</p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="features-icons-item mx-auto mb-0 mb-lg-3">
            <h3>New to the Job Market?</h3>
            <p class="lead mb-0">Black Cyber Recruiter's Job Seeker+ is almost here. Check it out today to see what your future can look like!</p>
          </div>
        </div>
      </div>
    </div>
    <hr>
  </section>
{% endblock %}

{% block secondSection %}
  <!-- Helpful Links -->
  <div class="container my-4">

    <!-- Wrapper-->
    <div id="multi-item-example" class="carousel slide carousel-multi-item" data-ride="carousel">

      <!--Slides-->
      <div class="carousel-inner" role="listbox">

        <!--3 Slides-->
        <div class="carousel-item active">

          <div class="row">
            <div class="col-md-4">
              <div class="card mb-2">
                <img class="card-img-top" src="https://i.pinimg.com/736x/17/3b/c5/173bc5119dd188f88d4a66752e7b1f3b.jpg"
                  alt="Chart img">
                <div class="card-body">
                  <h4 class="card-title">Black Unemployment Rate</h4>
                  <p class="card-text">Up to date Federal Reserve Economic Data graph highlighting black unemployment over time.</p>
                  <button class="btn btn-primary" onclick="location.href='https://fred.stlouisfed.org/series/LNS14000006'">Learn More</button>
                </div>
              </div>
            </div>

            <div class="col-md-4 clearfix d-none d-md-block">
              <div class="card mb-2">
                <img class="card-img-top" src="https://womensenews.org/wp-content/uploads/2018/04/black-woman-business-use-this-1170x695.jpg"
                  alt="Card image cap">
                <div class="card-body">
                  <h4 class="card-title">Black Labor Force</h4>
                  <p class="card-text">Data from U.S. Bureau of Labor Statistics identifying market activity of blacks in the U.S.</p>
                  <button class="btn btn-primary" onclick="location.href='https://www.bls.gov/spotlight/2020/african-american-history-month/home.htm'">Learn More</button>
                </div>
              </div>
            </div>

            <div class="col-md-4 clearfix d-none d-md-block">
              <div class="card mb-2">
                <img class="card-img-top" src="https://image.shutterstock.com/mosaic_250/2842531/272513510/stock-photo-closeup-of-resume-272513510.jpg"
                  alt="Card image cap">
                <div class="card-body">
                  <h4 class="card-title">14 Quick Job Tips</h4>
                  <p class="card-text">LiveCareer.com lays out 14 helpful tips to help you step up your game and get hired fast.</p>
                  <button class="btn btn-primary" onclick="location.href='https://www.livecareer.com/resources/jobs/search/14-job-hunting-tips'">Learn More</button>
                </div>
              </div>
            </div>
          </div>

        </div>
        <!--/.3 Slides-->

      </div>
      <!--/.Slides-->

    </div>
    <!--/.Wrapper-->

  </div>
{% endblock %}

  <!-- Footer -->
  <footer class="footer bg-light">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 h-100 text-center text-lg-left my-auto">
          <ul class="list-inline mb-2">
            <li class="list-inline-item">
              <a href="{% url 'Seekers:About' %}">About Us</a>
            </li>
            <li class="list-inline-item">&sdot;</li>
            <li class="list-inline-item">
              <a href="#">Contact</a>
            </li>
            <li class="list-inline-item">&sdot;</li>
            <li class="list-inline-item">
              <a href="#">Terms of Use</a>
            </li>
            <li class="list-inline-item">&sdot;</li>
            <li class="list-inline-item">
              <a href="#">Privacy Policy</a>
            </li>
          </ul>
          <p class="text-muted small mb-4 mb-lg-0">&copy; Black Cyber Recruiter. All Rights Reserved.</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <!-- <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script> -->

</body>

</html>