INTEX/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recruiters/', include('recruiters.urls')),
    path('', include('seekers.urls')),
]

recruiters/urls.py
from django.urls import path
import recruiters.views as v
from seekers.views import loginView

app_name = 'Recruiters'
urlpatterns = [
    # path("applicant_listings", v.applicantListingsView, name="Applicant Listings"),
    path("listing/addListing", v.AddListingView, name="CreateJob"),
    path('listing/editListing/<str:ListingID>', v.EditListingView, name='EditListing'),
    path('listing/deleteListing/<str:ListingID>', v.DeleteListingView, name='DeleteListing'),
    path('listing/addSkill/<str:ListingID>', v.AddListingSkill, name='AddListingSkill'),
    path('listing/editSkill/<str:ListingSkillID>', v.EditListingSkillView, name='EditListingSkill'),
    path('listing/deleteSkill/<str:ListingSkillID>', v.DeleteListingSkillView, name='DeleteListingSkill'),
    path("listing/applicants", v.applicantsView, name="Applicants"),
    path('listing/login/', loginView, name='Login'),
]   

seekers/urls.py
from django.urls import path
import seekers.views as v  

app_name = 'Seekers'
urlpatterns = [
    path("job_listings", v.jobListingsView, name="JobListings"),
    path("profile/<str:Type>/<str:userID>", v.profileView, name="Profile"),
    path("apply/<str:ListingID>", v.applicationView, name="Application"),
    # path("search", v.searchJob, name="Search"),
    # path('results', v.SearchResultsView, name='SearchResults'),
    path("create_account/<str:AccountType>", v.CreateAccountView, name="CreateAccount"),
    path("login", v.loginView, name="Login"),
    path("logout", v.logoutView,name="Logout"),
    path("about", v.about, name ="About"),
    path("add_skills", v.AddSeekerSkillsView, name="AddSkills"),
    path('editSkills/<str:SeekerSkillID>', v.EditSeekerSkillsView, name='EditSkills'),
    path('deleteSkills/<str:SeekerSkillID>', v.DeleteSeekerSkillsView, name='DeleteSkills'),
    path("search_bar/<str:SearchString>", v.SearchBar, name="SearchBar"),
    path("userApplications", v.userApplicationsView, name="UserApplication"),
    path("trending_jobs", v.recommenderDisplayView, name="TrendingJobs"),
    path("learn_more", v.learnMoreView, name="LearnMore"),
    path("", v.IndexPageView, name="Index"),
]   

seekers/forms.py
"""
Defines the forms used by the Seekers app.

Forms:
    RecruitersSignUpForm: allows an Anonymous User to sign up for a Recruiter account
    SeekersSignUpForm: allows an Anonymous User to sign up for a Job Seeker account
    LoginForm: allows a User to login 
    updateInfo: allows a Job Seeker to udpate their resume
    ListingSearch: allows a User to search Listings
    AddSkillsForm: allows a Job Seeker to add Skills to their profile
    applyForm: allows a Job Seeker to apply for a Listing
"""

# Python Imports
import re
# Django Imports
from django import forms
# App Imports
from recruiters import choices as rc
from seekers import choices as sc
from seekers import models as sm

#disable no-member syntax error
# pylint:disable=no-member

class _BaseSignUpForm(forms.Form) :
    """
    Base form used by Recruiter and SeekerSignUpForms.
    
    Contains common fields to both. Allows a User of the website to sign up as 
    either a Seeker or a Recruiter. Should not be used alone.

    Fields:
        first_name: CharField 
        last_name: CharField 
        email: EmailField 
        username: CharField 
        password: CharField(PasswordInput) 
        repeat_password: CharField(PasswordInput) 
    """
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField()
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    repeat_password = forms.CharField(widget=forms.PasswordInput)

    def clean_repeat_password(self) :
        if self.cleaned_data.get('password') != self.cleaned_data.get('repeat_password') :
            raise forms.ValidationError('The passwords do not match!')

class RecruiterSignUpForm(_BaseSignUpForm) :
    """
    Provides a Recruiter a way to sign up for an account.

    Fields : 
        email: EmailField 
        username: CharField 
        password: CharField(PasswordWidget) 
        repeat_password: CharField(PasswordWidget) 
        first_name: CharField 
        last_name: CharField 
        employee_job_title: CharField 
        org_name: CharField 
    """
    employee_job_title = forms.CharField(label='Your Job Title')
    org_name = forms.CharField()

    field_order = ['first_name', 'last_name', 'org_name', 'employee_job_title', 'email','username', 'password', 'repeat_password']


class SeekerSignUpForm(_BaseSignUpForm) :
    """
    Provides a Seeker a way to sign up for an account.

    Fields : 
        email: EmailField 
        username: CharField 
        password: CharField(PasswordWidget) 
        repeat_password: CharField(PasswordWidget) 
        first_name: CharField 
        last_name: CharField 
        phone: CharField 
    """
    phone = forms.CharField(max_length=15, required=False)
    # resume = forms.FileField(label='Resume')
    # skill = forms.ModelChoiceField(Skill.objects.all())

    # def clean_phone(self) :
    #     if self.cleaned_data.get('phone') is None :
    #         return
    #     match = re.search('^\d{15}$', self.cleaned_data.get('phone'))
    #     if match is None :
    #         raise ValidationError(message='The phone number you provided is not valid.')

    field_order = ['first_name', 'last_name', 'phone', 'email','username', 'password', 'repeat_password'] 


class LoginForm(forms.Form) :
    """
    Allows logging into the site.

    Fields: 
        username: CharField 
        password: CharField(PasswordInput) 
    """
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

# //TODO FUTURE 
# Gives Job Seekers a way to update thier info
class updateInfo(forms.Form) :
    """
    Form to allow a Job Seeker to upload a new resume. 

    Fields: 
        newResume: FileField 
    """
    newResume = forms.FileField()


class ListingSearch(forms.Form) :
    """
    Allows a User to search site Listings.

    Fields: 
        keyword: CharField 
    """
    keyword = forms.CharField()


class AddSkillsForm(forms.Form) :
    """
    Adds a skill to a Seeker.

    Fields: 
        skill: ModelChoiceField -> SkillObject 
        level: ChoiceField, choices SKILL_LEVEL 
    """
    skill = forms.ModelChoiceField(sm.Skill.objects.all())
    level = forms.ChoiceField(choices=sc.SKILL_LEVEL)


class applyForm(forms.Form) :
    """
    Allows a Seeker to apply for a Listing.

    Fields: 
        first_name: CharField 
        last_name: CharField 
        email: EmailField 
    """
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField()

seekers/views.py
"""
View functions for the Seekers app.

View Functions:
    about: returns the about page
    IndexPageView: returns the home page
    SearchBar: allows a User to search listings
    searchJob: performs the search and renders results
    jobListingView: returns all jobs
    profileView: shows a logged in user's profile
    applicationView: allows a Job Seeker to apply to a listing
    CreateAccountView: returns a blank form for an Anonymous User to 
        register an account as either a Job Seeker or a Recruiter
    loginView: allows a User with an account to log in
    logoutView: logs out a logged in User
    AddSeekerSkillsView: allows a Seeker to add skills to their profile
    EditSeekerSkillsView: allows a Seeker to edit their skills 
    DeleteSeekerSkillsView: allows deletion of a Seeker's skill
    userApplicationsView: shows a Seeker the Listings they've 
        applied to
    recommenderDisplayView: returns results for a specific User using 
        the AZURE recommender service
    learnMoreView: takes the User to the learn more page
"""
# Python Imports
import operator
import json 
import urllib.request as lib
# Django Imports
from django.contrib import messages
from django.db import IntegrityError
from django.forms import ValidationError
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.db.models import Q, ObjectDoesNotExist
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User, Group
from django.contrib.postgres.search import SearchQuery, SearchRank, SearchVector
# App Imports
from seekers.forms import SeekerSignUpForm, RecruiterSignUpForm, AddSkillsForm, LoginForm, applyForm
from seekers.models import Listing, Seeker, SeekerSkill, Skill, Application, ListingSkill
from recruiters.models import Recruiter

#pylint:disable=no-member

ACCOUNT_TYPES = {
    'R': 'recruiter',
    'S': 'seeker',
}

def about(request) :
    """
    Sends the user to the about page.
    GET:
        About contains data about our project. (black unemployment, 
        why we are creating this)

        Args:
            None
    """
    return render(request, 'seekers/aboutUs.html')

def IndexPageView(request) :
    """
    Home page of the website.

    GET:
        Landing page for the website and central hub.

        Args: 
            None
    """
    return render (request, 'seekers/index.html')

def SearchBar(request, SearchString) :
    """
    Allows a User to search all Listings.

    GET: 
        Performs a fuzzy search on location, job title, and org based 
        on a given search string and returns the results.

        Args:
            SearchString: str, keyword the user wants to search
    """
    search = request.GET.get('search')
    post = Listing.objects.all().filter( Q (listing_job_title__icontains = search) | Q (location__icontains = search) | Q (posted_by__org__icontains=search))
    context = {
        "listings" : post
    }
    return render(request, 'seekers/jobListings.html', context)

# TODO refactor out? Potentially not being used      
def searchJob(request) :
    """
    Allows a user to view all jobs matching a query string.
    """
    search = request.POST.get('search')

    return redirect(reverse('Seekers:SearchResults', kwargs={'SearchString': search}))

def jobListingsView(request) :
    """
    Shows the user a list of all job listings. 

    GET:
        If Anonymous or Seeker, shows all Listings. If a recruiter, 
        shows only the listings associated with the logged in 
        Recruiter's org.

        Args: 
            None
    """
    # checks if the current user is anonymous or a recruiter
    # if anonymous, show all listings
    if request.user.is_anonymous :
        data = Listing.objects.all()
    # if recruiter, then only show listing where the poster belongs to the recruiter's org
    elif request.user.has_perm('recruiters.is_recruiter') :
        data = Listing.objects.filter(posted_by__org=Recruiter.objects.get(user=request.user).org)
    # display all listings
    else :
        data = Listing.objects.all()

    context = {
        "listings" : data
    }
    return render (request, 'seekers/jobListings.html', context)

@login_required(login_url='/login')
def profileView(request, Type, userID) :
    """
    Allows the user to view their own profile information

    GET: 
        Sends the User to their profile. For a Seeker, shows their 
        skills. For a Recruiters, shows their listings.

        Args:
            Type: str, the account type of the user (Seeker, Recruiter)
            userID: str or int, pk of the User account
    """
    # check the type of account
    # if seeker, find the account and render it
    if Type == 'seeker' :
        try :
            data = Seeker.objects.get(user=request.user)
            skills = SeekerSkill.objects.filter(seeker__user=request.user)
        except ObjectDoesNotExist :
            return HttpResponse("we couldn't find your account. do you have one?")
        context = {
            "profile" : data,    
            "skills" : skills,
        }
        return render(request, 'seekers/profile.html', context=context)
    # if recruiter, find the account and render it
    elif Type == 'recruiter' :
        try :
            data = Recruiter.objects.get(user=request.user)
            jobs = Listing.objects.filter(posted_by=data)
        except ObjectDoesNotExist :
            return HttpResponse("we couldn't find your account. do you have one?")

        context = {
            "profile" : data,    
            "jobs" : jobs,
        }
        return render(request, 'seekers/profile.html', context=context)

    else :
        return HttpResponse("Not found")

@login_required(login_url='/login')
@permission_required('seekers.is_seeker', raise_exception=True)
def applicationView(request, ListingID) :
    """
    Allows a Seeker to apply to a Listing.

    GET: 
        Serves a blank application for the Seeker to review.
        
        Args:
            ListingID: str or int, pk of the Listing to apply to
    POST:
        Creates the Application object, binding the Seeker to the 
        Listing.
    """
    # checks if method is GET or POST
    # if GET, render blank form
    if request.method == 'GET' :
        # create blank form with intitial data from the user
        form = applyForm(initial={'first_name': request.user.first_name, 'last_name': request.user.last_name, 'email': request.user.email})
        currentSeeker = Seeker.objects.get(user=request.user)
        # //TODO zip up the skill level names
        context={
            "skills": SeekerSkill.objects.filter(seeker=currentSeeker),
            "form": form,
            "listing": Listing.objects.get(pk=ListingID),
            'listingSkills': ListingSkill.objects.filter(listing=Listing.objects.get(pk=ListingID)),
        } 
        return render(request, 'seekers/apply.html', context)
    # if POST, create an application object 
    elif request.method == 'POST' :
        form = applyForm(request.POST)
        # check if form is valid
        if form.is_valid() :
            # error handling in case they've already applied
            try :
                # creates the application object and sets the seeker and listing
                seeker = Seeker.objects.get(user=request.user)
                listing = Listing.objects.get(pk=ListingID)
                Application.objects.create(seeker=seeker, listing=listing)
            except IntegrityError :
                context = {
                    'error': 'You have already applied to this job!',
                    'errorjob': Application.objects.get(seeker=seeker, listing=listing),
                    'listings': Listing.objects.all(),
                }
                # renders the page with the error message
                return render (request, 'seekers/jobListings.html', context)
            # if object is created successfully, render the job listings page with a success message
            context = {
                'success': Application.objects.get(seeker=seeker, listing=listing),
                'listings': Listing.objects.all(),
            }
            # renders the page with the success message
            return render (request, 'seekers/jobListings.html', context)
        # invalid form
        else:
            return HttpResponse('Form not valid to create and application')
    # invalid method
    else :
        return HttpResponse('invalid method called')

def CreateAccountView(request, AccountType) :
    """
    Allows an anonymous user to create an account.

    GET:
        Returns a blank sign up form based on the type of account to 
        create.

        Args:
            AccountType: str, type of account to create ('S', 'R')
    POST:
        Creates the request account type. Sends the User to their 
        profile page. 
    """
    # check the method used in the request
    # if GET, return a blank form depending on the type of user they want to create
    if  request.method == 'GET' :
        if AccountType == 'S' :
            form = SeekerSignUpForm()
        elif AccountType == 'R' :
            form = RecruiterSignUpForm()
        else :
            # TODO add a custom error message
            # maybe give a 403 error page?
            return HttpResponse('not a valid account type')
        # render the create account page
        return render(request, 'seekers/createAccount.html', {'form': form, 'AccType': AccountType})
    # if POST, create account
    elif request.method == 'POST':
        # if valid account type, puts the data in the proper form
        if AccountType == 'S' :
            # form = SeekerSignUpForm(request.POST, request.FILES['resume'])
            form = SeekerSignUpForm(request.POST)

templates/seekers/addSkills.html
{% extends 'base.html' %}
{% load static %}

{% block nameOfTab %}
<title>Add A Skill</title>
{% endblock %}

{% block header %}
<div class="container">
    <h1>Add Your Skills and Their Associated Levels</h1>
</div>
{% endblock %}

{% block firstSection %}

<form action= "{{ request.path }}" method='POST' style="border:1px solid #ccc">
  <div class="container">
  <h4>Please select your skill and skill level.</h4>
  <br>
  
  {% csrf_token %}

  {{ form.non_field_errors }}

  {{ form.skill.label_tag }}
  {{ form.skill }}
  {{ form.skill.errors }}
  <br>
  {{ form.level.label_tag }}
  {{ form.level }}

    <div class="clearfix">
      {% if 'add_skill' in request.path %}
        <button type="submit" class="btn btn-primary" name="postJob">Add Skill</button>
      {% endif %}
      {% if 'editSkill' in request.path %}
        <button type="submit" class="btn btn-primary" name="saveChanges">Save Changes </button>
      {% endif %}
      {% if 'deleteSkill' in request.path %}
        <button type="submit" class="btn btn-primary" name="deleteJob">Delete Skill</button>
      {% endif %}
      <a href="{% url 'Seekers:Profile' Type='seeker' userID=request.user.pk %}"><button type="button" class="btn btn-primary">Cancel</button></a>
    </div>
  </div>
</form>
    
{% endblock %}

templates/seekers/applications.html
{% extends 'base.html' %}
{% load static %}

{% block nameOfTab %}
  <title>My Applications</title>
{% endblock %}

{% block header %}
<div class="container">
  <h1>APPLICATIONS</h1>
</div>
{% endblock %}


{% block firstSection %}

<div class="container">
  <div class="row rowForJobListings" style="border:groove black">
    <h3>Applications for {{ seeker.user.first_name }} {{ seeker.user.last_name }}</h3>
    <br>
    <ul>
      {% for application in applications %}
          <p>{{ forloop.counter }}. You applied for the {{ application.listing}} job on {{ application.date_applied}}</p>
      {% endfor %}
      <h5>Your current number of applications: {{ applications|length}} </h5>
    </ul>
  </div>
  <a href="{% url 'Seekers:Profile' Type='seeker' userID=request.user.pk %}"><button type="button" class="btn btn-primary">Back</button></a>
</div>
{% endblock %}

templates/seekers/apply.html
    {% extends 'base.html' %}
{% load static %}
{% load seekers_extras %}

{% block nameOfTab %}
<title>Apply</title>
{% endblock %}

{% block header %}
<div class="container">
  <h1>Review Information Before Applying</h1>
</div>
{% endblock %}

{% block firstSection %}

<form action= "{% url 'Seekers:Application' ListingID=listing.pk %}" method='POST' style="border:1px solid #ccc">
  <div class="container">
  <h4>Please verify the information is correct.</h4>
  <hr>
  <div class="form-column">
    {% csrf_token %}
    {{ form.first_name.label_tag }}
    {{ form.first_name }}

    {{ form.last_name.label_tag }}
    {{ form.last_name }}

    {{ form.email.label_tag }}
    {{ form.email }}
    </div>
    <h5>Your Skills:</h5>
    <ul>
    {% for skill in skills %}
      <li>{{ skill.skill.skill_name|title }} {{ skill.level|returnRating }}</li>
    {% endfor %}
    </ul>
    <h5>Skills for this Listing: </h5>
    <ul>
    {% for skill in listingSkills %}
      <li>{{ skill.skill.skill_name|title }} {{ skill.level|returnRating }}</li>
    {% endfor %}
    </ul>
    <div class="clearfix">
      <button type="submit" class="btn btn-primary">Apply</button>
      <a href="{% url 'Seekers:JobListings' %}"><button type="button" class="btn btn-primary">Cancel</button></a>
    </div>
  </div>
</form>

{% endblock %}

templates/seekers/createAccount.html
{% extends 'base.html' %}
{% load static %}

{% block nameOfTab %}
<title>Create Account</title>
{% endblock %}


{% block header %}
<div class="container">
    <h1>Create Account</h1>
</div>
{% endblock %}


{% block firstSection %}

<form enctype="multipart/form-data" action= "{% url 'Seekers:CreateAccount' AccountType=AccType%}" method='POST' style="border:1px solid #ccc">
  <div class="container">
  <h4>Please fill in this form to create an account.</h4>
  <hr>

  {% csrf_token %}

  {{ form.non_field_errors }}

  {% for field in form %}
    {{ field.label_tag}}
    {{ field }}
    {{ field.errors }}
    <br>
  {% endfor %}


  <div class="clearfix">
    <button type="submit" class="btn btn-primary">Sign Up</button>
    <a href="{% url 'Seekers:Login' %}"><button type="button" class="btn btn-primary">Cancel</button></a>
  </div>
  </div>
</form>

{% endblock %}

templates/seekers/index.html
{% extends 'base.html' %}
{% load static %}

{% block nameOfTab %}
  <title>Home Page</title>
{% endblock %}

templates/seekers/jobListings.html
{% extends 'base.html' %}
{% load static %}
{% load seekers_extras %}
{% load humanize %}

{% block nameOfTab %}
<title>Job Listings</title>
{% endblock %}

{% block header %}
<div class="container" >
  <h1 style="align-self: center;">Job Listings</h1>
    <div class="form-row">
      <div class="col-12 col-md-9 mb-2 mb-md-0">

        <form  action="{% url 'Seekers:SearchBar' SearchString='intern' %}" method='GET'>
          <input type="text" name='search' id='search' class="form-control form-control-lg" placeholder="Search by job title, location, company...">
          <button type="submit" class="btn btn-block btn-lg btn-primary" id='search_submit'>Search</button>
        </form>
      
      </div>
      <div class="col-12 col-md-3">
      
      </div>
    </div>
</div>

<br>

{% endblock %}

{% block firstSection %}
<!-- Page Content -->
 
<!-- If statement here to check if a related job was found. Do not display div if nothing was found.-->
<div class="container">

{% if error is not None %}
<h3>{{ error }}</h3>
<h5>{{ errorjob.listing.posted_by.org }}</h5>
<h5>{{ errorjob.listing.listing_job_title }}</h5>
<h5>{{ errorjob.date_applied }}</h5>
{% elif success is not None %}
<h3>You have successfully applied to "{{success.listing.listing_job_title}}".</h3>
<h4>Apply to more positions below, or view all your current applications in "Profile"</h4>
{% endif %}

  <h3>Job Results: {{ listings|length }}</h3>

  {% for job in listings %}
    <!-- Project One -->
    <div class="row rowForJobListings" style="border:groove black">
      <div class="col-md-5">
          <div class='listing-data'> <h3>Job Title:</h3> <div class='listing-data-center'>{{ job.listing_job_title }}</div></div>
          <div class='listing-data'> <h3>Company:</h3> <div class='listing-data-center'>{{ job.posted_by.org }}</div></div>
          <div class='listing-data'> <h3>Location:</h3> <div class='listing-data-center'>{{ job.location }}</div></div>
          <div class='listing-data'> <h5>Salary Range:</h5> <div class='listing-data-center'> ${{ job.salary_upper|intcomma}} -- ${{job.salary_lower|intcomma}}</div></div>
          <div class='listing-data'> <h5><div class='listing-data-center'>Relocation Assistance {{ job.relocation_assistance|returnReloc }}</div></div>
      </div>
      <div class="col-md-7">
        <h3>Summary</h3>
        <p>{{ job.job_description }}</p>
        <div class='listing-skills'>
          <h3>Skills</h3>
          <div class='listing-skill-row'>
            <div class='listing-skill-item'><h5>Skill</h5></div> 
            <div class='listing-skill-item'><h5>Level of Experience</h5></div> 
            <div class='listing-skill-item'></div>
          </div>
            {% for skill in job.listingskill_set.all  %}
              <div class='listing-skill-row'>
                <div class='listing-skill-item'>{{ skill.skill|title }}</div> 
                <div class='listing-skill-item'>{{ skill.level|returnRating }}</div> 
                <div class='listing-skill-item'>{% if skill.is_required %}Required{% else %}Preferred{% endif %}</div>
              </div>
            {% empty %}
              <p>No Skills Listed</p>
            {% endfor %}
        </div>
        {% if perms.seekers.is_seeker %}
          <a class="btn btn-primary" href="{% url 'Seekers:Application' ListingID=job.pk %}">Apply</a>
        {% elif perms.recruiters.is_recruiter %}
          <a class="btn btn-primary" href="{% url 'Recruiters:Applicants' %}">View Applicants</a>
        {% elif user.is_anonymous %}
          <a class="btn btn-primary" href="{% url 'Seekers:Login' %}">Login to Apply!</a>
        {% endif %}
      </div>
    </div>
    <!-- /.row -->
    <hr>
  {% endfor %}
  <h3><a href='#top'>Back to the Top!</a></h3>
</div>
{% endblock %}

{% block secondSection %}
{% endblock %}

templates/seekers/profile.html
{% extends 'base.html' %}
{% load static %}
{% load seekers_extras %}

{% block nameOfTab %}
<title>Profile</title>
{% endblock %}

{% block header %}
<div class="container">
  <h1>Profile for {{ profile.user.first_name }} {{ profile.user.last_name }} </h1>
  <div class="row rowForJobListings" style="border:groove black">
    <div class="col-lg-12">
      <h3>Username: {{ profile.user.username }}</h3>
      <h3>Email: {{ profile.user.email }}</h3>

      {% if perms.recruiters.is_recruiter %}
        <h3>Organization: {{ profile.org }}</h3>
      {% elif perms.seekers.is_seeker %}
        <h3>Phone: {{ profile.phone }}</h3> 
      {% endif %}

      {% if perms.seekers.is_seeker %}
      <div class='seeker-skill-row'>
        <div class='seeker-skill-skill-description'><h3>Skill</h3></div>
        <div class='seeker-skill-skill-description'><h3>Rating</h3></div>
        <div class='seeker-skill-button'></div> 
        <div class='seeker-skill-button'></div> 
      </div>
        {% for skill in skills %}
          <div class='seeker-skill-row'>
            <div class='seeker-skill-skill-description'>{{ skill.skill.skill_name|title}}</div>
            <div class='seeker-skill-skill-description'>{{ skill.level|returnRating }}</div>
            <div class='seeker-skill-button'><a href="{% url 'Seekers:EditSkills' SeekerSkillID=skill.pk %}"><button type="button" class="btn btn-primary">Edit</button></a></div> 
            <div class='seeker-skill-button'><a href="{% url 'Seekers:DeleteSkills' SeekerSkillID=skill.pk %}"><button type="button" class="btn btn-primary">Delete</button></a></div> 
          </div>
        {% empty %}
          <div class='skill-item'>You currently have no skills attached to your account. Use the Add Skills button to attach skills to your account.</div>
        {% endfor %}
      <div class="profile-footer">
        <a href="{% url 'Seekers:AddSkills' %}"><button type="submit" class="btn btn-primary">Add A Skill</button></a>
        <a href="{% url 'Seekers:UserApplication' %}"><button type="submit" class="btn btn-primary">My Applications</button></a>
      </div>

      {% elif perms.recruiters.is_recruiter %}
      <div class='profile-listing-row header'>
        <div class='profile-listing-description'> <h3> Job Title </h3> </div>
        <div class='profile-listing-description'> <h3> Location </h3> </div>
        <div class='profile-listing-description'> <h3> Contract </h3> </div>
        <div class='profile-listing-description'> <h3> Length </h3> </div>
        <div class='profile-listing-button'></div>
        <div class='profile-listing-button'></div>
      </div>
      {% for job in jobs %}
        <div class='profile-listing-row'>
          <div class='profile-listing-description'> {{ job.listing_job_title }} </div>
          <div class='profile-listing-description'> {{ job.location }} </div>
          <div class='profile-listing-description'> {{ job.contract_type }} </div>
          <div class='profile-listing-description'> {{ job.contract_length}} </div>
          <div class='profile-listing-button'><a href={% url 'Recruiters:EditListing' ListingID=job.pk %}><button type=button class="btn btn-primary">Edit</button></a></div>
          <div class='profile-listing-button'><a href={% url 'Recruiters:DeleteListing' ListingID=job.pk %}><button class="btn btn-primary" type=button>Delete</button></a></div>
        </div>
      {% empty %}
        <p>You currently have no jobs posted. Use the Add a Job button to post one!</p>
      {% endfor %}
      <div class="profile-footer">
        <a href="{% url 'Recruiters:CreateJob' %}"><button type="submit" class="btn btn-primary">Add A Job</button></a>
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock header %}

{% block firstSection %}
<p></p>
{% endblock %}